### ISSUE TITLE
Output problem

### ISSUE THREAD

**Issue by JJConesa** [Z-interpolation/IsoFlow#1]
Good morning. We are using isoflow with a stack of 156 images that were saved as single 8 bit tif files numbered from 0 with a xy pxl size of 6nm and z 30nm. We used the following command to run the interpolation:
isoflow -n 156 -f 5 -i slice_%03d.tif
The program renamed all slices properly (slice_155 was renamed as slice_775) but it only interpolated up to the renamed slice 155 generating a total of 280 images.
Could you please point were is the problem? Thank you in advance.
Javi Conesa

**Comment by vicente-gonzalez-ruiz** [comment]
Hi Javi,

thanks for using IsoFlow :-)

Please, could you provide the output of your interaction (copy and paste from your terminal)? I would like also to know the spatial resolution of your images.

**Comment by JJConesa** [comment]
Hi Vicente,

Thanks a lot for the fast answer!! Here the terminal output (there was no error) and the header of an image of the stack (by the end). Also related to the spatial resolution, the XY pxl size was 6 nm and 30 nm in Z.


isoflow -n 156 -f 5 -i slice_%03d.tif
(INFO) isoflow: renaming "slice_155.tif" to "slice_775.tif"
(INFO) isoflow: renaming "slice_154.tif" to "slice_770.tif"
(INFO) isoflow: renaming "slice_153.tif" to "slice_765.tif"
(INFO) isoflow: renaming "slice_152.tif" to "slice_760.tif"
(INFO) isoflow: renaming "slice_151.tif" to "slice_755.tif"
(INFO) isoflow: renaming "slice_150.tif" to "slice_750.tif"
(INFO) isoflow: renaming "slice_149.tif" to "slice_745.tif"
(INFO) isoflow: renaming "slice_148.tif" to "slice_740.tif"
(INFO) isoflow: renaming "slice_147.tif" to "slice_735.tif"
(INFO) isoflow: renaming "slice_146.tif" to "slice_730.tif"
(INFO) isoflow: renaming "slice_145.tif" to "slice_725.tif"
(INFO) isoflow: renaming "slice_144.tif" to "slice_720.tif"
(INFO) isoflow: renaming "slice_143.tif" to "slice_715.tif"
(INFO) isoflow: renaming "slice_142.tif" to "slice_710.tif"
(INFO) isoflow: renaming "slice_141.tif" to "slice_705.tif"
(INFO) isoflow: renaming "slice_140.tif" to "slice_700.tif"
(INFO) isoflow: renaming "slice_139.tif" to "slice_695.tif"
(INFO) isoflow: renaming "slice_138.tif" to "slice_690.tif"
(INFO) isoflow: renaming "slice_137.tif" to "slice_685.tif"
(INFO) isoflow: renaming "slice_136.tif" to "slice_680.tif"
(INFO) isoflow: renaming "slice_135.tif" to "slice_675.tif"
(INFO) isoflow: renaming "slice_134.tif" to "slice_670.tif"
(INFO) isoflow: renaming "slice_133.tif" to "slice_665.tif"
(INFO) isoflow: renaming "slice_132.tif" to "slice_660.tif"
(INFO) isoflow: renaming "slice_131.tif" to "slice_655.tif"
(INFO) isoflow: renaming "slice_130.tif" to "slice_650.tif"
(INFO) isoflow: renaming "slice_129.tif" to "slice_645.tif"
(INFO) isoflow: renaming "slice_128.tif" to "slice_640.tif"
(INFO) isoflow: renaming "slice_127.tif" to "slice_635.tif"
(INFO) isoflow: renaming "slice_126.tif" to "slice_630.tif"
(INFO) isoflow: renaming "slice_125.tif" to "slice_625.tif"
(INFO) isoflow: renaming "slice_124.tif" to "slice_620.tif"
(INFO) isoflow: renaming "slice_123.tif" to "slice_615.tif"
(INFO) isoflow: renaming "slice_122.tif" to "slice_610.tif"
(INFO) isoflow: renaming "slice_121.tif" to "slice_605.tif"
(INFO) isoflow: renaming "slice_120.tif" to "slice_600.tif"
(INFO) isoflow: renaming "slice_119.tif" to "slice_595.tif"
(INFO) isoflow: renaming "slice_118.tif" to "slice_590.tif"
(INFO) isoflow: renaming "slice_117.tif" to "slice_585.tif"
(INFO) isoflow: renaming "slice_116.tif" to "slice_580.tif"
(INFO) isoflow: renaming "slice_115.tif" to "slice_575.tif"
(INFO) isoflow: renaming "slice_114.tif" to "slice_570.tif"
(INFO) isoflow: renaming "slice_113.tif" to "slice_565.tif"
(INFO) isoflow: renaming "slice_112.tif" to "slice_560.tif"
(INFO) isoflow: renaming "slice_111.tif" to "slice_555.tif"
(INFO) isoflow: renaming "slice_110.tif" to "slice_550.tif"
(INFO) isoflow: renaming "slice_109.tif" to "slice_545.tif"
(INFO) isoflow: renaming "slice_108.tif" to "slice_540.tif"
(INFO) isoflow: renaming "slice_107.tif" to "slice_535.tif"
(INFO) isoflow: renaming "slice_106.tif" to "slice_530.tif"
(INFO) isoflow: renaming "slice_105.tif" to "slice_525.tif"
(INFO) isoflow: renaming "slice_104.tif" to "slice_520.tif"
(INFO) isoflow: renaming "slice_103.tif" to "slice_515.tif"
(INFO) isoflow: renaming "slice_102.tif" to "slice_510.tif"
(INFO) isoflow: renaming "slice_101.tif" to "slice_505.tif"
(INFO) isoflow: renaming "slice_100.tif" to "slice_500.tif"
(INFO) isoflow: renaming "slice_099.tif" to "slice_495.tif"
(INFO) isoflow: renaming "slice_098.tif" to "slice_490.tif"
(INFO) isoflow: renaming "slice_097.tif" to "slice_485.tif"
(INFO) isoflow: renaming "slice_096.tif" to "slice_480.tif"
(INFO) isoflow: renaming "slice_095.tif" to "slice_475.tif"
(INFO) isoflow: renaming "slice_094.tif" to "slice_470.tif"
(INFO) isoflow: renaming "slice_093.tif" to "slice_465.tif"
(INFO) isoflow: renaming "slice_092.tif" to "slice_460.tif"
(INFO) isoflow: renaming "slice_091.tif" to "slice_455.tif"
(INFO) isoflow: renaming "slice_090.tif" to "slice_450.tif"
(INFO) isoflow: renaming "slice_089.tif" to "slice_445.tif"
(INFO) isoflow: renaming "slice_088.tif" to "slice_440.tif"
(INFO) isoflow: renaming "slice_087.tif" to "slice_435.tif"
(INFO) isoflow: renaming "slice_086.tif" to "slice_430.tif"
(INFO) isoflow: renaming "slice_085.tif" to "slice_425.tif"
(INFO) isoflow: renaming "slice_084.tif" to "slice_420.tif"
(INFO) isoflow: renaming "slice_083.tif" to "slice_415.tif"
(INFO) isoflow: renaming "slice_082.tif" to "slice_410.tif"
(INFO) isoflow: renaming "slice_081.tif" to "slice_405.tif"
(INFO) isoflow: renaming "slice_080.tif" to "slice_400.tif"
(INFO) isoflow: renaming "slice_079.tif" to "slice_395.tif"
(INFO) isoflow: renaming "slice_078.tif" to "slice_390.tif"
(INFO) isoflow: renaming "slice_077.tif" to "slice_385.tif"
(INFO) isoflow: renaming "slice_076.tif" to "slice_380.tif"
(INFO) isoflow: renaming "slice_075.tif" to "slice_375.tif"
(INFO) isoflow: renaming "slice_074.tif" to "slice_370.tif"
(INFO) isoflow: renaming "slice_073.tif" to "slice_365.tif"
(INFO) isoflow: renaming "slice_072.tif" to "slice_360.tif"
(INFO) isoflow: renaming "slice_071.tif" to "slice_355.tif"
(INFO) isoflow: renaming "slice_070.tif" to "slice_350.tif"
(INFO) isoflow: renaming "slice_069.tif" to "slice_345.tif"
(INFO) isoflow: renaming "slice_068.tif" to "slice_340.tif"
(INFO) isoflow: renaming "slice_067.tif" to "slice_335.tif"
(INFO) isoflow: renaming "slice_066.tif" to "slice_330.tif"
(INFO) isoflow: renaming "slice_065.tif" to "slice_325.tif"
(INFO) isoflow: renaming "slice_064.tif" to "slice_320.tif"
(INFO) isoflow: renaming "slice_063.tif" to "slice_315.tif"
(INFO) isoflow: renaming "slice_062.tif" to "slice_310.tif"
(INFO) isoflow: renaming "slice_061.tif" to "slice_305.tif"
(INFO) isoflow: renaming "slice_060.tif" to "slice_300.tif"
(INFO) isoflow: renaming "slice_059.tif" to "slice_295.tif"
(INFO) isoflow: renaming "slice_058.tif" to "slice_290.tif"
(INFO) isoflow: renaming "slice_057.tif" to "slice_285.tif"
(INFO) isoflow: renaming "slice_056.tif" to "slice_280.tif"
(INFO) isoflow: renaming "slice_055.tif" to "slice_275.tif"
(INFO) isoflow: renaming "slice_054.tif" to "slice_270.tif"
(INFO) isoflow: renaming "slice_053.tif" to "slice_265.tif"
(INFO) isoflow: renaming "slice_052.tif" to "slice_260.tif"
(INFO) isoflow: renaming "slice_051.tif" to "slice_255.tif"
(INFO) isoflow: renaming "slice_050.tif" to "slice_250.tif"
(INFO) isoflow: renaming "slice_049.tif" to "slice_245.tif"
(INFO) isoflow: renaming "slice_048.tif" to "slice_240.tif"
(INFO) isoflow: renaming "slice_047.tif" to "slice_235.tif"
(INFO) isoflow: renaming "slice_046.tif" to "slice_230.tif"
(INFO) isoflow: renaming "slice_045.tif" to "slice_225.tif"
(INFO) isoflow: renaming "slice_044.tif" to "slice_220.tif"
(INFO) isoflow: renaming "slice_043.tif" to "slice_215.tif"
(INFO) isoflow: renaming "slice_042.tif" to "slice_210.tif"
(INFO) isoflow: renaming "slice_041.tif" to "slice_205.tif"
(INFO) isoflow: renaming "slice_040.tif" to "slice_200.tif"
(INFO) isoflow: renaming "slice_039.tif" to "slice_195.tif"
(INFO) isoflow: renaming "slice_038.tif" to "slice_190.tif"
(INFO) isoflow: renaming "slice_037.tif" to "slice_185.tif"
(INFO) isoflow: renaming "slice_036.tif" to "slice_180.tif"
(INFO) isoflow: renaming "slice_035.tif" to "slice_175.tif"
(INFO) isoflow: renaming "slice_034.tif" to "slice_170.tif"
(INFO) isoflow: renaming "slice_033.tif" to "slice_165.tif"
(INFO) isoflow: renaming "slice_032.tif" to "slice_160.tif"
(INFO) isoflow: renaming "slice_031.tif" to "slice_155.tif"
(INFO) isoflow: renaming "slice_030.tif" to "slice_150.tif"
(INFO) isoflow: renaming "slice_029.tif" to "slice_145.tif"
(INFO) isoflow: renaming "slice_028.tif" to "slice_140.tif"
(INFO) isoflow: renaming "slice_027.tif" to "slice_135.tif"
(INFO) isoflow: renaming "slice_026.tif" to "slice_130.tif"
(INFO) isoflow: renaming "slice_025.tif" to "slice_125.tif"
(INFO) isoflow: renaming "slice_024.tif" to "slice_120.tif"
(INFO) isoflow: renaming "slice_023.tif" to "slice_115.tif"
(INFO) isoflow: renaming "slice_022.tif" to "slice_110.tif"
(INFO) isoflow: renaming "slice_021.tif" to "slice_105.tif"
(INFO) isoflow: renaming "slice_020.tif" to "slice_100.tif"
(INFO) isoflow: renaming "slice_019.tif" to "slice_095.tif"
(INFO) isoflow: renaming "slice_018.tif" to "slice_090.tif"
(INFO) isoflow: renaming "slice_017.tif" to "slice_085.tif"
(INFO) isoflow: renaming "slice_016.tif" to "slice_080.tif"
(INFO) isoflow: renaming "slice_015.tif" to "slice_075.tif"
(INFO) isoflow: renaming "slice_014.tif" to "slice_070.tif"
(INFO) isoflow: renaming "slice_013.tif" to "slice_065.tif"
(INFO) isoflow: renaming "slice_012.tif" to "slice_060.tif"
(INFO) isoflow: renaming "slice_011.tif" to "slice_055.tif"
(INFO) isoflow: renaming "slice_010.tif" to "slice_050.tif"
(INFO) isoflow: renaming "slice_009.tif" to "slice_045.tif"
(INFO) isoflow: renaming "slice_008.tif" to "slice_040.tif"
(INFO) isoflow: renaming "slice_007.tif" to "slice_035.tif"
(INFO) isoflow: renaming "slice_006.tif" to "slice_030.tif"
(INFO) isoflow: renaming "slice_005.tif" to "slice_025.tif"
(INFO) isoflow: renaming "slice_004.tif" to "slice_020.tif"
(INFO) isoflow: renaming "slice_003.tif" to "slice_015.tif"
(INFO) isoflow: renaming "slice_002.tif" to "slice_010.tif"
(INFO) isoflow: renaming "slice_001.tif" to "slice_005.tif"
(INFO) isoflow: renaming "slice_000.tif" to "slice_000.tif"
(INFO) isoflow: reading image "slice_000.tif"
(INFO) isoflow: reading image "slice_005.tif"
(INFO) isoflow: CPU time = 12.184544149 seconds
(INFO) isoflow: writting image "slice_001.tif"
(INFO) isoflow: CPU time = 12.194771715999998 seconds
(INFO) isoflow: writting image "slice_002.tif"
(INFO) isoflow: CPU time = 12.178036931000005 seconds
(INFO) isoflow: writting image "slice_003.tif"
(INFO) isoflow: CPU time = 12.034463304999996 seconds
(INFO) isoflow: writting image "slice_004.tif"
(INFO) isoflow: reading image "slice_005.tif"
(INFO) isoflow: reading image "slice_010.tif"
(INFO) isoflow: CPU time = 12.173360927999994 seconds
(INFO) isoflow: writting image "slice_006.tif"
(INFO) isoflow: CPU time = 12.209712870999994 seconds
(INFO) isoflow: writting image "slice_007.tif"
(INFO) isoflow: CPU time = 12.053725404000005 seconds
(INFO) isoflow: writting image "slice_008.tif"
(INFO) isoflow: CPU time = 12.070339547000003 seconds
(INFO) isoflow: writting image "slice_009.tif"
(INFO) isoflow: reading image "slice_010.tif"
(INFO) isoflow: reading image "slice_015.tif"
(INFO) isoflow: CPU time = 12.023763236000008 seconds
(INFO) isoflow: writting image "slice_011.tif"
(INFO) isoflow: CPU time = 12.16598290399999 seconds
(INFO) isoflow: writting image "slice_012.tif"
(INFO) isoflow: CPU time = 12.042399408000009 seconds
(INFO) isoflow: writting image "slice_013.tif"
(INFO) isoflow: CPU time = 11.994440207999986 seconds
(INFO) isoflow: writting image "slice_014.tif"
(INFO) isoflow: reading image "slice_015.tif"
(INFO) isoflow: reading image "slice_020.tif"
(INFO) isoflow: CPU time = 12.107851693000015 seconds
(INFO) isoflow: writting image "slice_016.tif"
(INFO) isoflow: CPU time = 12.092848371999992 seconds
(INFO) isoflow: writting image "slice_017.tif"
(INFO) isoflow: CPU time = 12.108634450000011 seconds
(INFO) isoflow: writting image "slice_018.tif"
(INFO) isoflow: CPU time = 12.091172268000008 seconds
(INFO) isoflow: writting image "slice_019.tif"
(INFO) isoflow: reading image "slice_020.tif"
(INFO) isoflow: reading image "slice_025.tif"
(INFO) isoflow: CPU time = 12.007152269000017 seconds
(INFO) isoflow: writting image "slice_021.tif"
(INFO) isoflow: CPU time = 12.149905861999997 seconds
(INFO) isoflow: writting image "slice_022.tif"
(INFO) isoflow: CPU time = 12.049993395000001 seconds
(INFO) isoflow: writting image "slice_023.tif"
(INFO) isoflow: CPU time = 12.099253188000006 seconds
(INFO) isoflow: writting image "slice_024.tif"
(INFO) isoflow: reading image "slice_025.tif"
(INFO) isoflow: reading image "slice_030.tif"
(INFO) isoflow: CPU time = 12.092088576000009 seconds
(INFO) isoflow: writting image "slice_026.tif"
(INFO) isoflow: CPU time = 12.123272486000019 seconds
(INFO) isoflow: writting image "slice_027.tif"
(INFO) isoflow: CPU time = 12.069271046999972 seconds
(INFO) isoflow: writting image "slice_028.tif"
(INFO) isoflow: CPU time = 12.081567570000004 seconds
(INFO) isoflow: writting image "slice_029.tif"
(INFO) isoflow: reading image "slice_030.tif"
(INFO) isoflow: reading image "slice_035.tif"
(INFO) isoflow: CPU time = 12.06396580300003 seconds
(INFO) isoflow: writting image "slice_031.tif"
(INFO) isoflow: CPU time = 12.104865810999968 seconds
(INFO) isoflow: writting image "slice_032.tif"
(INFO) isoflow: CPU time = 12.035782764999965 seconds
(INFO) isoflow: writting image "slice_033.tif"
(INFO) isoflow: CPU time = 12.052163627000027 seconds
(INFO) isoflow: writting image "slice_034.tif"
(INFO) isoflow: reading image "slice_035.tif"
(INFO) isoflow: reading image "slice_040.tif"
(INFO) isoflow: CPU time = 12.165955261999954 seconds
(INFO) isoflow: writting image "slice_036.tif"
(INFO) isoflow: CPU time = 12.149639751999985 seconds
(INFO) isoflow: writting image "slice_037.tif"
(INFO) isoflow: CPU time = 12.106938786 seconds
(INFO) isoflow: writting image "slice_038.tif"
(INFO) isoflow: CPU time = 12.053407489999984 seconds
(INFO) isoflow: writting image "slice_039.tif"
(INFO) isoflow: reading image "slice_040.tif"
(INFO) isoflow: reading image "slice_045.tif"
(INFO) isoflow: CPU time = 12.004175696000004 seconds
(INFO) isoflow: writting image "slice_041.tif"
(INFO) isoflow: CPU time = 12.228448907000029 seconds
(INFO) isoflow: writting image "slice_042.tif"
(INFO) isoflow: CPU time = 12.035755007999967 seconds
(INFO) isoflow: writting image "slice_043.tif"
(INFO) isoflow: CPU time = 12.019209528999966 seconds
(INFO) isoflow: writting image "slice_044.tif"
(INFO) isoflow: reading image "slice_045.tif"
(INFO) isoflow: reading image "slice_050.tif"
(INFO) isoflow: CPU time = 12.074854722999987 seconds
(INFO) isoflow: writting image "slice_046.tif"
(INFO) isoflow: CPU time = 12.047627643999988 seconds
(INFO) isoflow: writting image "slice_047.tif"
(INFO) isoflow: CPU time = 12.180303267 seconds
(INFO) isoflow: writting image "slice_048.tif"
(INFO) isoflow: CPU time = 12.028360694000014 seconds
(INFO) isoflow: writting image "slice_049.tif"
(INFO) isoflow: reading image "slice_050.tif"
(INFO) isoflow: reading image "slice_055.tif"
(INFO) isoflow: CPU time = 12.021736946999965 seconds
(INFO) isoflow: writting image "slice_051.tif"
(INFO) isoflow: CPU time = 12.124531605000016 seconds
(INFO) isoflow: writting image "slice_052.tif"
(INFO) isoflow: CPU time = 12.231917248999935 seconds
(INFO) isoflow: writting image "slice_053.tif"
(INFO) isoflow: CPU time = 12.073432540999988 seconds
(INFO) isoflow: writting image "slice_054.tif"
(INFO) isoflow: reading image "slice_055.tif"
(INFO) isoflow: reading image "slice_060.tif"
(INFO) isoflow: CPU time = 12.072305237000023 seconds
(INFO) isoflow: writting image "slice_056.tif"
(INFO) isoflow: CPU time = 12.204270811000015 seconds
(INFO) isoflow: writting image "slice_057.tif"
(INFO) isoflow: CPU time = 12.12410683600001 seconds
(INFO) isoflow: writting image "slice_058.tif"
(INFO) isoflow: CPU time = 12.076159463999943 seconds
(INFO) isoflow: writting image "slice_059.tif"
(INFO) isoflow: reading image "slice_060.tif"
(INFO) isoflow: reading image "slice_065.tif"
(INFO) isoflow: CPU time = 12.045619372000033 seconds
(INFO) isoflow: writting image "slice_061.tif"
(INFO) isoflow: CPU time = 12.186012749000042 seconds
(INFO) isoflow: writting image "slice_062.tif"
(INFO) isoflow: CPU time = 12.048745639000003 seconds
(INFO) isoflow: writting image "slice_063.tif"
(INFO) isoflow: CPU time = 12.08772774099998 seconds
(INFO) isoflow: writting image "slice_064.tif"
(INFO) isoflow: reading image "slice_065.tif"
(INFO) isoflow: reading image "slice_070.tif"
(INFO) isoflow: CPU time = 12.056912167000064 seconds
(INFO) isoflow: writting image "slice_066.tif"
(INFO) isoflow: CPU time = 12.129499626999973 seconds
(INFO) isoflow: writting image "slice_067.tif"
(INFO) isoflow: CPU time = 12.049812821000046 seconds
(INFO) isoflow: writting image "slice_068.tif"
(INFO) isoflow: CPU time = 12.023876070999904 seconds
(INFO) isoflow: writting image "slice_069.tif"
(INFO) isoflow: reading image "slice_070.tif"
(INFO) isoflow: reading image "slice_075.tif"
(INFO) isoflow: CPU time = 11.971560006999994 seconds
(INFO) isoflow: writting image "slice_071.tif"
(INFO) isoflow: CPU time = 12.268648662000032 seconds
(INFO) isoflow: writting image "slice_072.tif"
(INFO) isoflow: CPU time = 12.085443294999891 seconds
(INFO) isoflow: writting image "slice_073.tif"
(INFO) isoflow: CPU time = 12.095631342000047 seconds
(INFO) isoflow: writting image "slice_074.tif"
(INFO) isoflow: reading image "slice_075.tif"
(INFO) isoflow: reading image "slice_080.tif"
(INFO) isoflow: CPU time = 12.086595596999928 seconds
(INFO) isoflow: writting image "slice_076.tif"
(INFO) isoflow: CPU time = 12.11704263699994 seconds
(INFO) isoflow: writting image "slice_077.tif"
(INFO) isoflow: CPU time = 12.097787823999965 seconds
(INFO) isoflow: writting image "slice_078.tif"
(INFO) isoflow: CPU time = 12.081298570000058 seconds
(INFO) isoflow: writting image "slice_079.tif"
(INFO) isoflow: reading image "slice_080.tif"
(INFO) isoflow: reading image "slice_085.tif"
(INFO) isoflow: CPU time = 11.963522522000062 seconds
(INFO) isoflow: writting image "slice_081.tif"
(INFO) isoflow: CPU time = 12.124139836999916 seconds
(INFO) isoflow: writting image "slice_082.tif"
(INFO) isoflow: CPU time = 12.052865895000082 seconds
(INFO) isoflow: writting image "slice_083.tif"
(INFO) isoflow: CPU time = 12.027203993000057 seconds
(INFO) isoflow: writting image "slice_084.tif"
(INFO) isoflow: reading image "slice_085.tif"
(INFO) isoflow: reading image "slice_090.tif"
(INFO) isoflow: CPU time = 12.030840858000033 seconds
(INFO) isoflow: writting image "slice_086.tif"
(INFO) isoflow: CPU time = 12.064340256000037 seconds
(INFO) isoflow: writting image "slice_087.tif"
(INFO) isoflow: CPU time = 12.036389210999914 seconds
(INFO) isoflow: writting image "slice_088.tif"
(INFO) isoflow: CPU time = 11.993137741000055 seconds
(INFO) isoflow: writting image "slice_089.tif"
(INFO) isoflow: reading image "slice_090.tif"
(INFO) isoflow: reading image "slice_095.tif"
(INFO) isoflow: CPU time = 12.216484948000016 seconds
(INFO) isoflow: writting image "slice_091.tif"
(INFO) isoflow: CPU time = 12.109723513000063 seconds
(INFO) isoflow: writting image "slice_092.tif"
(INFO) isoflow: CPU time = 12.05076753100002 seconds
(INFO) isoflow: writting image "slice_093.tif"
(INFO) isoflow: CPU time = 12.074471943999924 seconds
(INFO) isoflow: writting image "slice_094.tif"
(INFO) isoflow: reading image "slice_095.tif"
(INFO) isoflow: reading image "slice_100.tif"
(INFO) isoflow: CPU time = 11.941401025000005 seconds
(INFO) isoflow: writting image "slice_096.tif"
(INFO) isoflow: CPU time = 12.108560455999964 seconds
(INFO) isoflow: writting image "slice_097.tif"
(INFO) isoflow: CPU time = 12.047643845000039 seconds
(INFO) isoflow: writting image "slice_098.tif"
(INFO) isoflow: CPU time = 12.02893541200001 seconds
(INFO) isoflow: writting image "slice_099.tif"
(INFO) isoflow: reading image "slice_100.tif"
(INFO) isoflow: reading image "slice_105.tif"
(INFO) isoflow: CPU time = 12.020001535999995 seconds
(INFO) isoflow: writting image "slice_101.tif"
(INFO) isoflow: CPU time = 12.109924503000002 seconds
(INFO) isoflow: writting image "slice_102.tif"
(INFO) isoflow: CPU time = 12.01054031800004 seconds
(INFO) isoflow: writting image "slice_103.tif"
(INFO) isoflow: CPU time = 12.033184013999971 seconds
(INFO) isoflow: writting image "slice_104.tif"
(INFO) isoflow: reading image "slice_105.tif"
(INFO) isoflow: reading image "slice_110.tif"
(INFO) isoflow: CPU time = 12.061298767000153 seconds
(INFO) isoflow: writting image "slice_106.tif"
(INFO) isoflow: CPU time = 12.098933450999994 seconds
(INFO) isoflow: writting image "slice_107.tif"
(INFO) isoflow: CPU time = 12.094255591000092 seconds
(INFO) isoflow: writting image "slice_108.tif"
(INFO) isoflow: CPU time = 12.047569287999977 seconds
(INFO) isoflow: writting image "slice_109.tif"
(INFO) isoflow: reading image "slice_110.tif"
(INFO) isoflow: reading image "slice_115.tif"
(INFO) isoflow: CPU time = 12.144953128999987 seconds
(INFO) isoflow: writting image "slice_111.tif"
(INFO) isoflow: CPU time = 12.120157712000037 seconds
(INFO) isoflow: writting image "slice_112.tif"
(INFO) isoflow: CPU time = 12.168919392999896 seconds
(INFO) isoflow: writting image "slice_113.tif"
(INFO) isoflow: CPU time = 12.136699172999897 seconds
(INFO) isoflow: writting image "slice_114.tif"
(INFO) isoflow: reading image "slice_115.tif"
(INFO) isoflow: reading image "slice_120.tif"
(INFO) isoflow: CPU time = 11.985172675000058 seconds
(INFO) isoflow: writting image "slice_116.tif"
(INFO) isoflow: CPU time = 12.101150903999951 seconds
(INFO) isoflow: writting image "slice_117.tif"
(INFO) isoflow: CPU time = 12.042435164999915 seconds
(INFO) isoflow: writting image "slice_118.tif"
(INFO) isoflow: CPU time = 12.005442720000019 seconds
(INFO) isoflow: writting image "slice_119.tif"
(INFO) isoflow: reading image "slice_120.tif"
(INFO) isoflow: reading image "slice_125.tif"
(INFO) isoflow: CPU time = 12.15397594000001 seconds
(INFO) isoflow: writting image "slice_121.tif"
(INFO) isoflow: CPU time = 12.162476863999927 seconds
(INFO) isoflow: writting image "slice_122.tif"
(INFO) isoflow: CPU time = 12.04778763499985 seconds
(INFO) isoflow: writting image "slice_123.tif"
(INFO) isoflow: CPU time = 12.081799717000195 seconds
(INFO) isoflow: writting image "slice_124.tif"
(INFO) isoflow: reading image "slice_125.tif"
(INFO) isoflow: reading image "slice_130.tif"
(INFO) isoflow: CPU time = 11.953489673999911 seconds
(INFO) isoflow: writting image "slice_126.tif"
(INFO) isoflow: CPU time = 12.08615048699994 seconds
(INFO) isoflow: writting image "slice_127.tif"
(INFO) isoflow: CPU time = 11.972589454999934 seconds
(INFO) isoflow: writting image "slice_128.tif"
(INFO) isoflow: CPU time = 12.0191665320001 seconds
(INFO) isoflow: writting image "slice_129.tif"
(INFO) isoflow: reading image "slice_130.tif"
(INFO) isoflow: reading image "slice_135.tif"
(INFO) isoflow: CPU time = 11.984973086000082 seconds
(INFO) isoflow: writting image "slice_131.tif"
(INFO) isoflow: CPU time = 12.18066302699981 seconds
(INFO) isoflow: writting image "slice_132.tif"
(INFO) isoflow: CPU time = 12.104998526000145 seconds
(INFO) isoflow: writting image "slice_133.tif"
(INFO) isoflow: CPU time = 12.051441216000057 seconds
(INFO) isoflow: writting image "slice_134.tif"
(INFO) isoflow: reading image "slice_135.tif"
(INFO) isoflow: reading image "slice_140.tif"
(INFO) isoflow: CPU time = 12.058827977999954 seconds
(INFO) isoflow: writting image "slice_136.tif"
(INFO) isoflow: CPU time = 12.121063044000039 seconds
(INFO) isoflow: writting image "slice_137.tif"
(INFO) isoflow: CPU time = 12.054244569000048 seconds
(INFO) isoflow: writting image "slice_138.tif"
(INFO) isoflow: CPU time = 12.001517264999848 seconds
(INFO) isoflow: writting image "slice_139.tif"
(INFO) isoflow: reading image "slice_140.tif"
(INFO) isoflow: reading image "slice_145.tif"
(INFO) isoflow: CPU time = 12.019165613999803 seconds
(INFO) isoflow: writting image "slice_141.tif"
(INFO) isoflow: CPU time = 12.130809736999936 seconds
(INFO) isoflow: writting image "slice_142.tif"
(INFO) isoflow: CPU time = 12.1534103219999 seconds
(INFO) isoflow: writting image "slice_143.tif"
(INFO) isoflow: CPU time = 12.055117500000051 seconds
(INFO) isoflow: writting image "slice_144.tif"
(INFO) isoflow: reading image "slice_145.tif"
(INFO) isoflow: reading image "slice_150.tif"
(INFO) isoflow: CPU time = 12.05465703599998 seconds
(INFO) isoflow: writting image "slice_146.tif"
(INFO) isoflow: CPU time = 12.124394497999901 seconds
(INFO) isoflow: writting image "slice_147.tif"
(INFO) isoflow: CPU time = 12.023368671000071 seconds
(INFO) isoflow: writting image "slice_148.tif"
(INFO) isoflow: CPU time = 12.00967133600011 seconds
(INFO) isoflow: writting image "slice_149.tif"
(INFO) isoflow: reading image "slice_150.tif"
(INFO) isoflow: reading image "slice_155.tif"
(INFO) isoflow: CPU time = 12.11824568499992 seconds
(INFO) isoflow: writting image "slice_151.tif"
(INFO) isoflow: CPU time = 12.065101636000009 seconds
(INFO) isoflow: writting image "slice_152.tif"
(INFO) isoflow: CPU time = 12.041498453000031 seconds
(INFO) isoflow: writting image "slice_153.tif"
(INFO) isoflow: CPU time = 12.135335071999862 seconds
(INFO) isoflow: writting image "slice_154.tif"


** Running command:  xmipp_image_header "-i" "slice_000.tif"
Input File: slice_000.tif

--- File information ---
Filename       : slice_000.tif
Endianess      : Big
Reversed       : True
Data type      : Unsigned character or byte type (UInt8)
Data offset    : 0
--- Image information ---
Image type     : Real-space image
Dimensions     : 1 x 1 x 3500 x 3180  ((N)Objects x (Z)Slices x (Y)Rows x (X)Columns)
Sampling rate  :
                 X-rate (Angstrom/pixel) = 1
                 Y-rate (Angstrom/pixel) = 1
                 Z-rate (Angstrom/pixel) = 1

**Comment by vicente-gonzalez-ruiz** [comment]
Hi again,

thank you for the info. Yes, there was a bug in the code, that now should be fixed. Please, let me know if now is working properly.

You have two options to update your code: (1) clone again the repo or (2) run "git pull".

Best regards,
Vicente.

**Comment by JJConesa** [comment]
Hi Vicente,
Now it is working! Thanks a lot.

Best,
Javi Conesa
